.\" Manpage for livemap-config.
.TH man 1 "03 Jan 2023" "1.0" "livemap-config man page"
.SH NAME
livemap-config \- Live Sectional Map LED/OLED management
.SH SYNOPSIS
config.ini
.SH DESCRIPTION
Standard config.ini formatted configuration file
.SH OPTIONS
default \- Global Configuration Settings
.P
modules \- Which discrete modules are enabled
.P
filenames \- Definition for filenames for discrete files
.P
urls \- Definition of external HTTP/S URLS for data sources
.P
metar \- Metar related configuration
.P
schedule \- Night time On/Off timer information
.P
maps \- Default MAP Lat/Lon
.P
oled \- OLED specific configuration
.P
colors \- Default Colors in hex format
.P
lights \- Default LED behavior
.P
rotaryswitch \- Rotaryswitch details
.P
.SH SEE ALSO
livemap(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Chris Higgins (chris.higgins@alternoc.net)
