.\" Manpage for livemap.
.TH man 1 "03 Jan 2023" "1.0" "livemap man page"
.SH NAME
livemap.py \- Live Sectional Map LED/OLED management
.SH SYNOPSIS
livemap.py
.SH DESCRIPTION
livemap is a python daemon that downloads Airport weather data and uses that data to update LED, OLED connected to Raspberry PI GPIO pins to display live airport weather data
.SH OPTIONS
livemap.py does not take any options ; but uses config.ini
.SH SEE ALSO
livemap-config(5)
.SH BUGS
No known bugs.
.SH AUTHOR
Chris Higgins (chris.higgins@alternoc.net)